# Generated by Django 4.2 on 2024-12-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="actividades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("horario", models.TimeField()),
                ("profesor", models.CharField(max_length=50)),
                ("descripcion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="socios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("dni", models.CharField(max_length=10, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="sucursales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("direccion", models.CharField(max_length=100)),
            ],
        ),
    ]
